### ISSUE TITLE
[Cinnamon] Software Manager won't launch if Flatpak is removed

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/mint21-beta#164]
**Describe the bug**
If Flatpak is removed, and the system receives some updates through Update Manager, Software Manager does not launch.

**To Reproduce**
1. Remove Flatpak with `apt remove flatpak`.
2. Receive some updates from the Update Manager.
3. Launch Software Manager with `mintinstall`.
4. See error:
```
 ➜ mintinstall
MintInstall: Detected system architecture: 'x86_64'
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 635, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 154, in init_sync
    if self._fp_remotes_have_changed():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 229, in _fp_remotes_have_changed
    fp_remotes = self.list_flatpak_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 346, in list_flatpak_remotes
    return _flatpak.list_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 810, in list_remotes
    fp_sys = get_fp_sys()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 68, in get_fp_sys
    _fp_sys = Flatpak.Installation.new_system(None)
gi.repository.GLib.GError: g-io-error-quark: While opening repository /var/lib/flatpak/repo: opening repo: opendir(/var/lib/flatpak/repo): No such file or directory (1)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintinstall_mintinstall.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 635, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 154, in init_sync
    if self._fp_remotes_have_changed():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 229, in _fp_remotes_have_changed
    fp_remotes = self.list_flatpak_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 346, in list_flatpak_remotes
    return _flatpak.list_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 810, in list_remotes
    fp_sys = get_fp_sys()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 68, in get_fp_sys
    _fp_sys = Flatpak.Installation.new_system(None)
gi.repository.GLib.GError: g-io-error-quark: While opening repository /var/lib/flatpak/repo: opening repo: opendir(/var/lib/flatpak/repo): No such file or directory (1)
```

**Expected behavior**
Software Manager should launch in all cases.

**Hardware and mintUpdate**
* Is your system all up-to-date ? ***YES.***

**Additional context**
Here is the problem again:
1. Remove flatpak `apt remove flatpak`
2. Receive updates from Update Manager
3. Software Manager `mintinstall` fails to launch 
The following fixes the problem:
4. Now reinstall Flatpak `apt install flatpak`
5. Now Software Manager launches OK.
6. Now Flatpak can be removed again with `apt remove flatpak`.
7. Software Manager still launches OK. 
8. When the next update is received from Update Manager, the issue comes back. It happened in this cycle 4-5 times so far. Every time, installing/removing Flatpak fixes the issue.

**Comment by Acheron17** [comment]
Confirming the failure is repeatable.

**Comment by mtwebster** [comment]
I can't reproduce this.

> Receive updates from Update Manager

What does that mean?

Did you *install* some updates? Or did you just refresh and there are new updates available?

Was this done on a clean install immediately after installation? Or did you run mintinstall, then remove it, then try to run again?

What if you remove `gir1.2-flatpak-1.0` along with `flatpak`?

**Comment by spamegg1** [comment]
> Receive updates from Update Manager
> What does that mean?

Sorry, I meant I installed some available updates. 

> Was this done on a clean install immediately after installation? Or did you run mintinstall, then remove it, then try to run again?

Yes, after a clean install of Mint 21 Beta I immediately removed `flatpak`. Then there were updates available in Update Manager, which I installed. Then running `mintinstall` gave the above error. I did not install/remove mintinstall itself.

Then I re-installed and re-removed `flatpak`. Everything OK. `mintinstall` launches. Few days later I installed some available updates from Update Manager again. Same problem again. And so on. This happened 4-5 times since the Beta started. Probably would happen more often but I wasn't paying attention (since I never use Flatpak or Software Manager).

> What if you remove `gir1.2-flatpak-1.0` along with `flatpak`?

I'll try that! Gotta wait until the next available update...

**Comment by Acheron17** [comment]
Did a quick fresh install, removed flatpak and gir1.2-flatpak-1.0, did some updates and then launched mintinstall from the command prompt.

mintinstall
MintInstall: Detected system architecture: 'x86_64'
No flatpak support, install flatpak and gir1.2-flatpak-1.0 and restart mintinstall to enable it.
Installer: Generating new pkgcache
Installer: Processing APT packages for cache took 1157.129 ms
Full installer startup took 1431.313 ms
MintInstall: Cannot open reviews cache: [Errno 2] No such file or directory: '/home/harry/.cache/mintinstall/reviews.json'
MintInstall: Deleting old screenshots
MintInstall: Downloaded new reviews

Will wait for the original poster to confirm.
